swagger: '2.0'
info:
  description: Test endpoints
  version: 1.0.0
  title: Test API
  termsOfService: TERMS OF SERVICE URL
host: localhost
basePath: /
tags:
  - name: Book Operations
    description: Book related operations
paths:
  /v1/books:
    post:
      summary: Save books
      operationId: saveBook
      produces:
        - application/json
      parameters:
        - name: requestId
          in: header
          description: Globally unique Request Id for the request.
          required: true
          type: string
          x-example: req1234
        - name: bookVo
          in: body
          schema:
            $ref: '#/definitions/BookVO'
      responses:
        '200':
          description: Successful
          schema:
            $ref: '#/definitions/BookVO'
        '400':
          description: Bad request / Validation error in given data
        '401':
          description: You are not authorized to view the resource
        '403':
          description: Accessing the resource you were trying to reach is forbidden
        '404':
          description: Resource you were trying to reach not found.
        '500':
          description: Internal Server / Technical Error
  /v1/books/{id}:
    get:
      summary: Get book by Id
      operationId: retrieveBook
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Successful
          schema:
            $ref: '#/definitions/BookVO'
        '400':
          description: Bad request / Validation error in given data
        '401':
          description: You are not authorized to view the resource
        '403':
          description: Accessing the resource you were trying to reach is forbidden
        '404':
          description: Resource you were trying to reach not found
        '500':
          description: Internal Server / Technical Error
definitions:
  BookVO:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
    title: BookVO